Data:
  Path: "data.csv"
  Separator: ","
  Encoding: "utf-8"
  Header: True
  Text Column: "Customer Feedback"
  Label Columns:
    - "Delivery Issue"
    - "Product Quality"
    - "Customer Service"
    - "Pricing"
  Multi Label: True
  Require Confirmation: False

Output:
  Path: "output.csv"
  Separator: ","
  Encoding: "utf-8"
  Header: True

Top Bar:
  Title: "EasyLabel"
  Framed: False
  Location: "top"
